/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElHeader: (typeof import("element-plus/es"))["ElHeader"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElPagination: (typeof import("element-plus/es"))["ElPagination"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElTable: (typeof import("element-plus/es"))["ElTable"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    ElTableItem: (typeof import("element-plus/es"))["ElTableItem"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ElTree: (typeof import("element-plus/es"))["ElTree"];
    IEpUser: (typeof import("~icons/ep/user"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
